# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Chattice CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  server-build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server
        
    steps:
    - uses: actions/checkout@v4
    - name: Build and Run Server tests
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
        cache-dependency-path: ./server/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present


  client-build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
    - uses: actions/checkout@v4
    - name: Build and Run Client tests
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
        cache-dependency-path: ./client/package.lock.json
    - run: npm ci
    - run: npm run build -if-present
    - run: npm test -if-present
    
